<table class="GameContentHeader">
<tr align="center">
<td class="icon"><div id="##GAMECONTENTID##" class="loading"></div></td>
<td class="gameName"><a href="javascript:postwith('/game/gamedetails.html?contenttype=##GAMECONTENTTYPE##&titleid=##GAMETITLEID##&contentid=##GAMECONTENTID##', {sessionid:'##SESSIONID##'})">##GAMENAME##</a></td>
<td class="titleID">##GAMETITLEID##</td><td class="gamePath">##GAMEPATH##</td>
</tr>
</table> 
