#pragma once
#include "../Managers/GameList/GameListItem.h"
#include "../Generic/tools.h"

class GameListItem;

#define FSDTRANSITION_TRANSTOIMAGE	0
#define FSDTRANSITION_BLACKTOIMAGE	1
#define FSDTRANSITION_SLIDEINIMAGE	2

#define FSDTRANSNAME_STARTOPT1		L"StartFaderOption1"
#define FSDTRANSNAME_ENDOPT1		L"EndFaderOption1"
#define FSDTRANSNAME_STARTOPT2		L"StartFaderOption2"
#define FSDTRANSNAME_ENDOPT2		L"EndFaderOption2"
#define FSDTRANSNAME_STARTOPT3		L"StartFaderOption3"
#define FSDTRANSNAME_ENDOPT3		L"EndFaderOption3"

#define FSDIMAGE_GAMEICON			0
#define FSDIMAGE_GAMEBOXART			1
#define FSDIMAGE_GAMEBANNER			2
#define FSDIMAGE_GAMEBACKGROUND		3
#define FSDIMAGE_GAMESCREENSHOT1	4
#define FSDIMAGE_GAMESCREENSHOT2	5
#define FSDIMAGE_GAMEFAVORITE		6

#define FSDIMAGE_GAMERATINGSTARBASE 11
#define FSDIMAGE_GAMERATINGSTAR1	11	
#define FSDIMAGE_GAMERATINGSTAR2	12
#define FSDIMAGE_GAMERATINGSTAR3	13
#define FSDIMAGE_GAMERATINGSTAR4	14
#define FSDIMAGE_GAMERATINGSTAR5	15

#define FSDTEXT_MAINTITLE			0
#define FSDTEXT_SUBTITLE			1
#define FSDTEXT_GAMEID				2
#define FSDTEXT_GAMETITLE			3
#define FSDTEXT_GAMEDEVELOPER		4
#define FSDTEXT_GAMEDEVICEID		5


// User Rating Texture Index
#define FSDIMAGE_000STAR			0
#define FSDIMAGE_025STAR			1
#define FSDIMAGE_050STAR			2
#define FSDIMAGE_075STAR			3
#define FSDIMAGE_100STAR			4
#define FSDRATING_MAXSTARCOUNT		5

typedef enum  _GAMELIST_SUBTITLEVIEW {
	GAMELIST_SUBTITLEVIEW_FIRST = 0,
	GAMELIST_SUBTITLEVIEW_VIEW1 = 0,
	GAMELIST_SUBTITLEVIEW_VIEW2 = 1,
	GAMELIST_SUBTITLEVIEW_VIEW3 = 2,
	GAMELIST_SUBTITLEVIEW_LAST = 2
} GAMELIST_SUBTITLEVIEW;

typedef enum _GAMELIST_SORTSTYLE{
	GAMELIST_SORTSTYLE_FIRST = 0,
	GAMELIST_SORTSTYLE_ALPHA = 0,
	GAMELIST_SORTSTYLE_RATING = 1,
	GAMELIST_SORTSTYLE_RATERS = 2,
	GAMELIST_SORTSTYLE_RELEASEDATE = 3,
	GAMELIST_SORTSTYLE_LASTPLAYEDDATE = 4,
	GAMELIST_SORTSTYLE_USERRATING = 5,
	GAMELIST_SORTSTYLE_LAST = 5
} GAMELIST_SORTSTYLE;

typedef enum _GAMELIST_SORTDIRECTION{
	GAMELIST_SORTDIRECTION_FIRST = 0,
	GAMELIST_SORTDIRECTION_FORWARD = 0,
	GAMELIST_SORTDIRECTION_BACKWARD = 1,
	GAMELIST_SORTDIRECTION_LAST = 1
} GAMELIST_SORTDIRECTION;

typedef struct _GAMECONTENT_LIST_STATE {
	int ListSize;
	int CurrentIndex;
	int PreviousIndex;
	GAMELIST_SORTSTYLE SortStyle;
	GAMELIST_SORTDIRECTION SortDirection;
	GAMELIST_SUBTITLEVIEW SubTitleView;
	GameListItem * CurrentGame;
	GameListItem * PreviousGame;
} GAMECONTENT_LIST_STATE, *PGAMECONTENT_LIST_STATE;

typedef struct _GAMECONTENT_LIST_SETTINGS {
	string MissingIconPath;
	string MissingBoxartPath;
	string MissingBannerPath;
	string MissingScreenshotPath;
	string LoadingIconPath;
	string LoadingBoxartPath;
	string LoadingBannerPath;
	string LoadingScreenshotPath;
	string StarFavoritePath;
	string StarRatingPath[FSDRATING_MAXSTARCOUNT];
} GAMECONTENT_LIST_SETTINGS, *PGAMECONTENT_LIST_SETTINGS;
